---

- block:
    - name: apt | remove conflicting packages with gift repository
      apt: name={{ timesketch_gift_remove }} state=absent
      register: pkg_result
      until: pkg_result is success
  when: timesketch_gift_remove is defined and timesketch_gift_remove != []

- name: apt | timesketch packages dependencies
  apt: name={{ timesketch_pkg }} state=present update_cache=yes cache_valid_time=3600
  register: pkg_result
  until: pkg_result is success

- name: Ubuntu | add universe repository
  apt_repository: repo="deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe" state=present
  when: ansible_distribution == 'Ubuntu'

- block:
    - name: Install OpenJDK
      apt: name={{ timesketch_jdk }} state=latest
      register: pkg_result
      until: pkg_result is success

    - name: Download Elasticsearch v1
      get_url:
        url: "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.5.deb"
        dest: /root/elasticsearch-1.7.5.deb
        mode: '0644'
    - name: Install Elasticsearch v1
      apt: deb="/root/elasticsearch-1.7.5.deb" state=present
      register: pkg_result
      until: pkg_result is success
  when: timesketch_with_elasticv1 is defined and timesketch_with_elasticv1
