---
## https://github.com/google/timesketch/wiki/Installation

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
# - name: Include OS-specific variables for Fedora.
#   include_vars: "{{ ansible_distribution }}.yml"
#   when: ansible_distribution == 'Fedora'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat"

- import_tasks: native.yml
  when: timesketch_setup == 'native'

- import_tasks: docker.yml
  when: timesketch_setup == 'docker'
