---

- name: Ensure openssl is present
  package:
    name: openssl
    state: present

- name: generate random secret
  shell: |
    set -o pipefail
    openssl rand -base64 32 | sed 's@[=\\/\\+]@@g;' | tee /root/.timesketch_secret
  args:
    creates: "/root/.timesketch_secret"
    executable: /bin/bash
  register: rand
  changed_when: false
  no_log: "{{ timesketch_no_log | default(true) }}"

- name: Get existing secret fact
  command: cat /root/.timesketch_secret
  register: rand
  changed_when: false
  no_log: "{{ timesketch_no_log | default(true) }}"
